server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook_db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: phonebook

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: phonebook

  thymeleaf:
    check-template-location: false