server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phonebook_db
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_schema: phonebook

  thymeleaf:
    check-template-location: false